_wandb:
    value:
        cli_version: 0.21.3
        e:
            qyzuzcm0k8t8uxw70ivpu595olxjlr09:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "71400898560"
                        used: "30031286272"
                email: wildanaziz@student.ub.ac.id
                executable: /home/wildanaziz/yolo_auto_train/yolo-auto/bin/python3
                host: wildanaziz-ThinkPad-L13-Yoga
                memory:
                    total: "7887343616"
                os: Linux-6.8.0-78-generic-x86_64-with-glibc2.35
                program: /home/wildanaziz/yolo_auto_train/train.py
                python: CPython 3.12.7
                root: /home/wildanaziz/yolo_auto_train
                startedAt: "2025-09-01T14:27:22.554407Z"
                writerId: qyzuzcm0k8t8uxw70ivpu595olxjlr09
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
            "4": 3.12.7
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
